# Generated by Django 4.2 on 2025-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="User's physical location address",
                null=True,
                verbose_name="Physical Address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="user",
            name="farm_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Farm size in acres (for farmers only)",
                max_digits=10,
                null=True,
                verbose_name="Farm Size",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has been verified by the system",
                verbose_name="Verified Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="User's primary contact number",
                max_length=15,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("agronomist", "Agronomist"),
                    ("technician", "Technician"),
                    ("admin", "System Administrator"),
                ],
                default="farmer",
                help_text="The role determines the user's permissions and access level",
                max_length=20,
                verbose_name="User Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="Area of expertise (for agronomists/technicians)",
                max_length=100,
                null=True,
                verbose_name="Specialization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_user_role_36d76d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified"], name="users_user_is_veri_9ce429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="users_user_created_cf865c_idx"
            ),
        ),
    ]
