# Generated by Django 4.2 on 2025-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low", "Below Threshold"),
                            ("high", "Above Threshold"),
                            ("malfunction", "Sensor Malfunction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "reading_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Field area in hectares",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("crop_type", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SANDY", "Sandy"),
                            ("CLAY", "Clay"),
                            ("LOAM", "Loam"),
                            ("SILT", "Silt"),
                            ("PEAT", "Peat"),
                            ("CHALKY", "Chalky"),
                        ],
                        help_text="Predominant soil type in this field",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "planting_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when crops were planted in this field",
                        null=True,
                    ),
                ),
                (
                    "geometry",
                    models.TextField(
                        blank=True,
                        help_text="GeoJSON or other spatial data representing the field boundary",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or description about this field",
                        null=True,
                    ),
                ),
                (
                    "irrigation_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRIP", "Drip Irrigation"),
                            ("SPRINKLER", "Sprinkler System"),
                            ("FLOOD", "Flood Irrigation"),
                            ("NONE", "None"),
                        ],
                        help_text="Type of irrigation system used",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Check if this field is currently active for monitoring",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
