# Generated by Django 5.2.3 on 2025-07-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
        ("fields", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="farms.farm",
            ),
        ),
    ]
