# Generated by Django 4.2 on 2025-06-29 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_collection_farms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
