# Generated by Django 5.2.3 on 2025-07-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                (
                    "total_fields",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of fields in this farm"
                    ),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total farm area in acres",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "ordering": ["-created_at"],
            },
        ),
    ]
