# Generated by Django 4.2 on 2025-06-29 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IrrigationZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("clay", "Clay"),
                            ("loam", "Loam"),
                            ("sand", "Sandy"),
                            ("silt", "Silt"),
                        ],
                        max_length=50,
                    ),
                ),
                ("plant_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "temperature_max",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "temperature_min",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("precipitation", models.DecimalField(decimal_places=2, max_digits=5)),
                ("wind_speed", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="IrrigationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("every_other_day", "Every Other Day"),
                            ("twice_weekly", "Twice Weekly"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("auto_weather_adjust", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irrigation.irrigationzone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IrrigationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_actual", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "water_volume_liters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("weather_condition", models.CharField(blank=True, max_length=50)),
                (
                    "soil_moisture_before",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "soil_moisture_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irrigation.irrigationschedule",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irrigation.irrigationzone",
                    ),
                ),
            ],
        ),
    ]
