# Generated by Django 5.2.3 on 2025-07-10 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irrigation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="irrigationschedule",
            old_name="duration",
            new_name="duration_minutes",
        ),
        migrations.AddField(
            model_name="irrigationschedule",
            name="auto_weather_adjust",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="irrigationschedule",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="irrigationschedule",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
